# https://docs.github.com/en/actions

name: "Release"
on:
  push:
    tags:
      - 'v*'
env:
  PHP_EXTENSIONS: "mbstring"
  PHP_INI_VALUES: "memory_limit=-1, phar.readonly=0"
jobs:
  release:
    name: "Release"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version:
          - "8.1"
        dependencies:
          - "locked"
    runs-on: ${{matrix.os}}
    env:
      G4M_PHAR: "autoupdate/stable/ankor.phar"
      BOX_VERSION: "3.16.0"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          php-version: "${{ matrix.php-version }}"
      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "vendor"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"
      - name: "Install dependencies"
        run: "composer install --no-progress"
        
      - name: Install Box
        run: |
          wget \
            "https://github.com/humbug/box/releases/download/${{ env.BOX_VERSION }}/box.phar" \
            --quiet \
            -O ./box
          chmod +x ./box
          sudo mv ./box /usr/local/bin
      - name: "Compile ankor.phar with humbug/box"
        run: "box compile --config=box.json"
      - name: "Determine tag"
        id: "get_version"
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Get Release
        id: get
        uses: philwc/get-release@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: text/plain
          asset_name: ankor-${{ env.tag }}
          asset_path: ankor-${{ env.tag }}
          upload_url: ${{ steps.get.outputs.upload_url }}
          